version: '3.7'

services:
  deep_learning:
    image: jhoeller/computer-vision:ultra
    volumes:
      - /app/:/app
    ports:
      - 8888:8888
    networks:
      - api_bridge
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 3  # num of gpus
            capabilities: [gpu]
    restart: always

  mlflow:
    image: jhoeller/mlflow-v.1.14.1:default
    ports:
      - 5000:5000
    volumes:
      - /mlflow:/mlflow
    networks:
      - api_bridge
    restart: always
    command: mlflow server --backend-store-uri sqlite:////mlflow/mlflow.sqlite --default-artifact-root /mlflow/artifacts --host 0.0.0.0 

  tensorboard:
    image: tensorflow/tensorflow
    networks:
      - api_bridge
    volumes:
      - /tensor:/notebooks
    ports:
      - 6006:6006
    command: tensorboard --logdir=/notebooks/graphs --bind_all

  model_serving:
    image: seldonio/mlflowserver:1.18.0-dev
    networks:
      - api_bridge
    ports:
      - 5555:5000   # grpc
      - 9992:9000   # rest
    environment:
      - MODEL_NAME=my_llm
      - SERVICE_TYPE=MODEL  # MODEL  ROUTER  TRANSFORMER  COMBINER  OUTLIER_DETECTOR

networks:
  api_bridge:
    driver: bridge

volumes:
  app_data:
  mlflow_data:
  tensor_data: